name: dart_package_from_scratch_by_wago 
description: My Dart Course Package.
version: 1.0.1
repository: https://github.com/edwardohazo/dart_package_from_scratch.git

environment:
  sdk: ^3.4.4

executables:
  wago_script: wago_script

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
